-- Placeholder migration: one-time clear of sales/sale_lines is NOT run automatically.
--
-- To clear all sales and receipt state use ONE of:
--   A) Admin API (preferred): POST /api/admin/clear-sales-history with body { "confirm": "CLEAR_ALL_SALES" }.
--      This calls the clear_sales_history() RPC (see 20260305230000).
--   B) In DB (emergency): run the statements in supabase/scripts/clear_sales_manual.sql
--        in order, with statement_timeout set if needed.
--
-- This file intentionally contains no DELETE/TRUNCATE so that applying migrations
-- never destroys data. Data integrity: destructive actions are explicit and audited.
