export function getAllProducts(): Promise<unknown[]>;
export function getProductById(id: string): Promise<unknown>;
export function addProduct(data: Record<string, unknown>): Promise<string>;
export function updateProduct(id: string, data: Record<string, unknown>): Promise<void>;
export function deleteProduct(id: string): Promise<void>;
export function mirrorProductsFromApi(apiProducts: unknown[]): Promise<void>;
export function getUnsyncedItems(): Promise<unknown[]>;
export function getSyncQueueItems(): Promise<unknown[]>;
export function getFailedQueueItems(): Promise<unknown[]>;
export function getAllSyncQueueItems(): Promise<unknown[]>;
export function exportAllData(): Promise<unknown>;
export function importFromBackup(backup: unknown, options?: { replace?: boolean }): Promise<{ productsAdded: number; queueAdded: number }>;
export function clearSyncQueue(): Promise<void>;
export function clearAllLocalProductData(): Promise<void>;
export function clearFailedQueueItems(): Promise<void>;
export function retryAllFailedQueueItems(): Promise<number>;
export function retryQueueItem(queueItemId: number): Promise<void>;
export function undoAddProduct(productId: string): Promise<void>;
export function setSyncError(productId: string, message: string): Promise<void>;
export function getSyncError(productId: string): Promise<unknown>;
export function clearSyncError(productId: string): Promise<void>;
export function getConflictPreference(): Promise<string | null>;
export function setConflictPreference(value: string): Promise<void>;
export function appendConflictAuditLog(entry: unknown): Promise<void>;
export const db: {
  products: { toArray(): Promise<unknown[]>; clear(): Promise<void>; count(): Promise<number> };
  syncQueue: {
    delete(id: number): Promise<void>;
    count(): Promise<number>;
    orderBy(index: string): { reverse(): { toArray(): Promise<unknown[]> }; toArray(): Promise<unknown[]> };
    where(index: string): { equals(value: string): { count(): Promise<number>; toArray(): Promise<unknown[]> } };
  };
};
